# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

string_split <- function(x, sep, num) {
    .Call('tgirthamr_string_split', PACKAGE = 'tgirthamr', x, sep, num)
}

mergeTypeList <- function(realbase) {
    .Call('tgirthamr_mergeTypeList', PACKAGE = 'tgirthamr', realbase)
}

heterozygote <- function(A, C, T, G, cov) {
    .Call('tgirthamr_heterozygote', PACKAGE = 'tgirthamr', A, C, T, G, cov)
}

transformDF <- function(df, seqErr, pCutOff, binom) {
    .Call('tgirthamr_transformDF', PACKAGE = 'tgirthamr', df, seqErr, pCutOff, binom)
}

